import os
from building import *

cwd = GetCurrentDir()

# 收集 soem 下的所有 .c 文件
soem_src = Glob('soem/*.c')

# 其他明确路径的 C 文件
other_src = Split('''
osal/intime/osal.c
oshw/intime/nicdrv.c
oshw/intime/oshw.c
test/intime/main.c
''')

src = soem_src + other_src

# 设置头文件搜索路径
path = [
    cwd,
    cwd + '/osal',              # <--- ✅ 包含 osal.h 的路径
    cwd + '/include',
    cwd + '/soem',
    cwd + '/oshw/intime',
    cwd + '/osal/intime',
    cwd + 'SOEM-1.3.0/osal'
]

# 创建构建组
group = DefineGroup('soem-1.3.0', src, depend=[''], CPPPATH=path)

print("包含路径 CPPPATH (path):")
for p in path:
    print(" -", p)

Return('group')
